pub mod accept;
pub mod adaptive_verify;
pub mod draft_vocab;
pub mod eagle3_engine;
pub mod engine;
pub mod model;
pub mod projection;
pub mod route_aware;
pub mod route_aware_drafter;
pub mod telemetry;
pub mod tree;
pub mod tree_shape;
pub mod types;

pub use adaptive_verify::{adaptive_verify_depth, emitted, expected_accepted, verify_cost, VerifyPlan};
pub use draft_vocab::DraftVocabMap;
pub use eagle3_engine::{AuxModelRunner, DecodeStop, Eagle3Config, Eagle3Engine, Eagle3RoundStats};
pub use engine::{SpecConfig, SpecEngine, RoundStats};
pub use model::{DrafterPool, ModelRunner};
pub use projection::{MeasuredAccept, RoundCostModel};
pub use route_aware::{Candidate, ExpertUnion, RouteAwarePolicy};
pub use route_aware_drafter::{CandidateSource, RouteAwareDrafter};
pub use telemetry::{SpecTelemetry, TelemetrySnapshot};
pub use tree::{accept_tree, SpecTree};
pub use tree_shape::{level_advance_prob, tree_expected_accepted, tree_nodes, TreeCostModel, TreeShape};
pub use types::{AcceptedRun, DraftProposal, DraftTree, RngCore, TargetLogits, TokenId};
